export enum SessionAuditAction {
  SESSION_CREATED = 'SESSION_CREATED',
  SESSION_EXPIRED = 'SESSION_EXPIRED',
  SESSION_REVOKED = 'SESSION_REVOKED',
  SESSION_LOGOUT = 'SESSION_LOGOUT',
  SESSION_REVOKED_ADMIN = 'SESSION_REVOKED_ADMIN',
  SESSION_REVOKED_PASSWORD_CHANGE = 'SESSION_REVOKED_PASSWORD_CHANGE',
  CONCURRENT_LOGIN_BLOCKED = 'CONCURRENT_LOGIN_BLOCKED',
  SESSION_REFRESHED = 'SESSION_REFRESHED',
  SESSION_VALIDATION_FAILED = 'SESSION_VALIDATION_FAILED',
  PASSWORD_RESET = "PASSWORD_RESET",
  ACCOUNT_DELETED = "ACCOUNT_DELETED",
}